#!/usr/bin/env python3

import argparse
import os
import sqlite3
import sys

class RTCmd:
    DATABASE_NAME = os.path.expanduser("~/.rtcmd.db3")

    def __init__(self):
        self._conn = sqlite3.connect(RTCmd.DATABASE_NAME)
        self._conn.row_factory = sqlite3.Row
        self._cur = self._conn.cursor()

        self._cur.execute("CREATE TABLE IF NOT EXISTS commands ("
                            "id INTEGER PRIMARY KEY,"
                            "tag TEXT NOT NULL,"
                            "command TEXT NOT NULL,"
                            "note TEXT)")

    def _print_cursor(self):
        rows = 0
        tag = None

        for row in self._cur:
            rows += 1
            if tag != row["tag"]:
                tag = row["tag"]
                print("\n--- {} ---".format(tag))

            print("{:5} | {}".format(row["id"], row["command"]))
            if row["note"]:
                print("      | {}".format(row["note"]))

        return rows

    def add(self, tag, command, note):
        self._cur.execute("INSERT INTO commands (tag, command, note) "
                          "VALUES(?, ?, ?)", (tag, command, note))

    def list(self, tag=None):
        if tag is not None:
            self._cur.execute("SELECT * FROM commands WHERE tag = ? "
                              "ORDER BY tag", (tag,))
        else:
            self._cur.execute("SELECT * FROM commands ORDER BY tag")

        rows = self._print_cursor()
        if rows == 0:
            print("Nothing to show")

    def remove(self, index):
        self._cur.execute("DELETE FROM commands WHERE id = ?", (index,))

    def search(self, term):
        self._cur.execute("SELECT * FROM commands WHERE command LIKE ? "
                          "OR note LIKE ?", (term, term))

        rows = self._print_cursor()
        if rows == 0:
            print("Nothing was found")

    def __del__(self):
        self._conn.commit()
        self._conn.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--command",
            help="command to remember")
    parser.add_argument("--delete", metavar="IDX",
            help="delete a saved command with a given index")
    parser.add_argument("--list", metavar="TAG", nargs="?", const="",
            help="list saved commands")
    parser.add_argument("--note",
            help="optional note")
    parser.add_argument("--search", metavar="TERM",
            help="Search in 'command' and 'note' fields (?, %% - wildcards)")
    parser.add_argument("--tag",
            help="tag for the given command")

    args = parser.parse_args()

    rtcmd = RTCmd()

    try:
        # ADD
        if args.tag and args.command:
            rtcmd.add(args.tag, args.command, args.note)
        # DELETE
        elif args.delete:
            rtcmd.remove(args.delete)
        # LIST
        elif args.list is not None:
            if len(args.list) == 0:
                args.list = None

            rtcmd.list(args.list)
        elif args.search:
            rtcmd.search(args.search)
        # INVALID ARGUMENTS
        else:
            parser.print_help()
            sys.exit(1)

    except Exception as e:
        print("Error: {}".format(e), file=sys.stderr)
        sys.exit(1)
